// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN3HvfBMxMr8j9RK0nNSp3NO0i-7eirJ8',
    appId: '1:1027587126449:android:4545fc69c51aae06315e90',
    messagingSenderId: '1027587126449',
    projectId: 'tripletrio-l1',
    databaseURL: 'https://tripletrio-l1.firebaseio.com',
    storageBucket: 'tripletrio-l1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClbiVmoWtVXOXYldDRqjLcilri-sm5rss',
    appId: '1:1027587126449:ios:c923dd3541ce3ca7315e90',
    messagingSenderId: '1027587126449',
    projectId: 'tripletrio-l1',
    databaseURL: 'https://tripletrio-l1.firebaseio.com',
    storageBucket: 'tripletrio-l1.appspot.com',
    androidClientId: '1027587126449-abrijo1dovaldfe05k9mr6uf77gorep2.apps.googleusercontent.com',
    iosClientId: '1027587126449-mk64bvo51hj0fp0trit6mh1i59etag0n.apps.googleusercontent.com',
    iosBundleId: 'tripletriolimited.distributor',
  );
}
